data_path: 'dataset/arts-scientifics/'
pq_data: MG
benchmark_filename: [train, valid, test]
alias_of_item_id: [item_id_list]
load_col:
  inter: [user_id, item_id_list, item_id]
neg_sampling: ~
transform: ~

topk: [10, 30, 50]
metrics: [Recall, NDCG]
valid_metric: Recall@10
stopping_step: 10
gpu_id : 0
learning_rate: 0.002
epoch: 100

train_stage: inductive_ft
pretrain_epochs: 100
save_step: 10
train_batch_size: 1280

index_path: dataset/movies-games
index_pretrain_dataset: G
filter_id_suffix: filtered_id
checkpoint_dir : 'save_MG/'